### ISSUE TITLE
how to import test_cases

### ISSUE THREAD

**Issue by nonovaliant** [msjit/testcasedb#86] opened 2015-03-06 09:21 UTC
we export test_cases and modify it to import, but failed.

![screenshot from 2015-03-06 17 36 01](https://cloud.githubusercontent.com/assets/11347581/6523087/4caebd8e-c427-11e4-81a6-747b8377549a.png)

![screenshot from 2015-03-06 17 37 55](https://cloud.githubusercontent.com/assets/11347581/6523111/8bbdbe30-c427-11e4-85ab-960c2c7fa232.png)

**Comment by joffems** [comment] 2015-03-09 04:14
Looking at your screenshot the description is using special characters. IF you remove the description does the import work?

**Comment by nonovaliant** [comment] 2015-03-11 08:10
no , it just is  chinese!

**Comment by joffems** [comment] 2015-03-23 01:01
Did you try removing the Chinese characters to see if makes a difference?

Also, the system is not designed to export data and then re-import. IF you need to edit test cases they should be edited in the system.

Closing for now as I don't think this is being used as intended. IF you can't import the standard test cases with Chinese characters, please create a new ticket.

**Closed by joffems** 2015-03-23 01:01 UTC
